name: cicd
run-name: ${{ github.actor }} isssestsdafdgdfgasdassding out OpenAPI spec validation
on: [push]
jobs:
  verify:
    uses: SielCode/github-utilities/.github/workflows/verify.yml@api_related_metadata_file_validation